#!/usr/bin/env php
<?php declare(strict_types=1);

use Composer\XdebugHandler\XdebugHandler;
use Symfony\Component\DependencyInjection\Container;
use Symplify\EasyCodingStandard\Console\Application;
use Symplify\PackageBuilder\Console\ThrowableRenderer;

require_once __DIR__ . '/vendor/symplify/easy-coding-standard/bin/autoload.php';

// performance boost
gc_disable();

$xdebug = new XdebugHandler('ecs', '--ansi');
$xdebug->check();
unset($xdebug);

try {
    /** @var Container $container */
    $container = require __DIR__ . '/vendor/symplify/easy-coding-standard/bin/container.php';

    /** @var Application $application */
    $application = $container->get(Application::class);
    exit($application->run());
} catch (Throwable $throwable) {
    (new ThrowableRenderer())->render($throwable);
    exit(1);
}
